const {chromium}=require('playwright');const {Store}=require('../desktop/store.cjs');const fs=require('node:fs');const path=require('node:path');const http=require('node:http');const os=require('node:os');const assert=require('node:assert/strict');
(async()=>{
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sb-ui-'));let store=new Store(dir,JSON.parse(fs.readFileSync('desktop/seed.json')));
const server=http.createServer((req,res)=>{let file=path.join(process.cwd(),'dist',new URL(req.url,'http://localhost').pathname);if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.resolve('dist/index.html');const ext=path.extname(file);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png'})[ext]||'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))requests.push(r.url());});
await page.exposeFunction('desktopRead',()=>store.snapshot());await page.exposeFunction('desktopCommit',(ops,rev)=>{const r=store.commit(ops,rev);if(r.changed)setImmediate(()=>page.evaluate(()=>window.dispatchEvent(new Event('local-changed'))).catch(()=>{}));return r;});
await page.exposeFunction('desktopBackup',()=>{throw Error('Simulated offline network. Local data is safe.');});
await page.addInitScript(()=>{Object.defineProperty(navigator,'onLine',{get:()=>false});window.systemBuilderDesktop={read:()=>window.desktopRead(),commit:(ops,rev)=>window.desktopCommit(ops,rev),backup:()=>window.desktopBackup(),exportLocal:async()=>true,onChange:fn=>{window.addEventListener('local-changed',fn);return()=>window.removeEventListener('local-changed',fn);}};});
try{
await page.goto(origin);await page.getByRole('button',{name:'Add Task',exact:true}).waitFor();
assert.equal(await page.getByText('Username',{exact:true}).count(),0);
await page.getByRole('button',{name:'Add Task',exact:true}).click();await page.getByPlaceholder('e.g., Complete chapter 4 of SQL fundamentals').fill('DESKTOP OFFLINE TEST');
await page.getByRole('dialog',{name:'Enter tasks'}).getByRole('button',{name:'Add',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('input[placeholder="e.g., Complete chapter 4 of SQL fundamentals"]')?.value==='');
await page.getByRole('button',{name:'Done',exact:true}).click();
const added=Object.values(store.state.collections.tasks).find(t=>t.title==='DESKTOP OFFLINE TEST');assert.ok(added);
await page.getByRole('checkbox',{name:'Mark completed: DESKTOP OFFLINE TEST',exact:true}).click();
await page.getByRole('checkbox',{name:'Mark incomplete: DESKTOP OFFLINE TEST',exact:true}).waitFor();
assert.equal(store.state.collections.tasks[added.taskId].Iscompleted,true);
store=new Store(dir,JSON.parse(fs.readFileSync('desktop/seed.json')));await page.reload();
await page.getByRole('checkbox',{name:'Mark incomplete: DESKTOP OFFLINE TEST',exact:true}).waitFor();
await page.getByRole('button',{name:'Open backup',exact:true}).first().click();
await page.getByRole('button',{name:'Back up to Firestore',exact:true}).click();
await page.getByRole('status').filter({hasText:'Simulated offline'}).waitFor();assert.equal(store.state.lastBackup,null);
await page.getByRole('button',{name:'Close backup',exact:true}).click();
await page.getByRole('button',{name:'Open Data Analytics',exact:true}).first().click();
await page.getByRole('heading',{name:'Data Analytics',exact:true}).waitFor();assert.equal(await page.getByLabel('Open AI data analyst').count(),0);
await page.getByRole('button',{name:'Back to Today',exact:false}).click();
await page.getByRole('button',{name:'Add Task',exact:true}).waitFor();
await page.getByRole('button',{name:'Open Books',exact:true}).first().click();
await page.getByRole('button',{name:'Open Home',exact:true}).first().waitFor();
assert.ok((await page.locator('body').innerText()).includes('Cal Newport'));
await page.getByRole('button',{name:'Open Home',exact:true}).first().click();
await page.getByRole('button',{name:'Open Tools',exact:true}).first().click();
await page.getByRole('button',{name:'Habit Tracker',exact:true}).click();
await page.getByText('Wake Up Early 5 AM',{exact:true}).first().waitFor();
await page.getByRole('button',{name:'Data',exact:true}).click();
await page.getByRole('table').first().waitFor();
assert.equal(await page.getByRole('button',{name:/Import or export .* data/}).count(),0);
await page.getByRole('button',{name:'Data Transfer'}).click();
await page.getByText('Export All',{exact:true}).waitFor();
await page.getByText('Import All',{exact:true}).waitFor();
assert.equal(await page.getByRole('menu').count(),1);
await page.getByRole('button',{name:'Data Transfer'}).click();

await page.getByRole('button',{name:'Open Home',exact:true}).first().click();
await page.getByRole('button',{name:'More actions for DESKTOP OFFLINE TEST',exact:true}).click();
await page.getByRole('button',{name:'Delete',exact:true}).click();
await page.getByRole('button',{name:'Delete Task',exact:true}).click();
await page.getByRole('dialog',{name:'Delete task',exact:true}).waitFor({state:'hidden'});
assert.equal(store.state.collections.tasks[added.taskId],undefined);
await page.getByLabel('System Builder loading screen').waitFor({state:'hidden'});
await page.screenshot({path:'desktop/home-preview.png',fullPage:true});
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
console.log('PASS: offline task create/complete/reopen, backup failure, analytics/home, books, habits, data, zero external requests and zero page errors.');
}catch(error){await page.screenshot({path:'desktop/ui-failure.png',fullPage:true});console.log((await page.locator('body').innerText()).slice(0,6000));console.log('Errors:',errors);throw error;}finally{await browser.close();server.close();fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
