import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {downloadArtifact} from '@electron/get';
import extract from 'extract-zip';
import {brandWindowsExecutable} from './windows-branding.mjs';
const require=createRequire(import.meta.url);
const version=require('electron/package.json').version;
const root=path.resolve('release/System-Builder-Desktop');
await fs.mkdir(root,{recursive:true});
const archive=await downloadArtifact({version,artifactName:'electron',platform:'win32',arch:'x64'});
await extract(archive,{dir:root});
await fs.rename(path.join(root,'electron.exe'),path.join(root,'System Builder.exe'));
await brandWindowsExecutable(path.join(root,'System Builder.exe'));
const target=path.join(root,'resources/app');await fs.mkdir(path.join(target,'desktop'),{recursive:true});
await fs.cp('dist',path.join(target,'dist'),{recursive:true});
for(const file of ['main.cjs','preload.cjs','store.cjs','backup.cjs','seed.json','system-builder.ico'])await fs.copyFile('desktop/'+file,path.join(target,'desktop',file));
await fs.copyFile('firebase-applet-config.json',path.join(target,'firebase-applet-config.json'));
await fs.writeFile(path.join(target,'package.json'),JSON.stringify({name:'system-builder-desktop',version:require('../package.json').version,main:'desktop/main.cjs'}));
await fs.copyFile('desktop/README.txt',path.join(root,'READ-ME-FIRST.txt'));
console.log('Windows x64 portable application created:',root);

